name: Prime Academy CI/CD Deploy to VPS

on:
  push:
    branches:
      - staging
      # - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dep.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.PRIME_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          source: "./"
          target: "/var/www/primeacademy/api"
          strip_components: 1
          rm: false

      - name: Restart app on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.PRIME_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |           
            cd /var/www/primeacademy/api
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt -r requirements-dep.txt
            python3 manage.py migrate
            sudo systemctl daemon-reload
            sudo systemctl restart primeacademy
            echo "Gunicorn service restarted successfully"
